# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_one', models.CharField(max_length=50)),
                ('email_two', models.CharField(max_length=50)),
            ],
        ),
    ]
