# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_by', models.CharField(max_length=50)),
            ],
        ),
    ]
