# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
